### ISSUE TITLE
Support validating `initialValue` for Fields

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/houseform#13]
Currently, we do not validate the initial value of fields on HouseForm. We should support this using an `onMountValidate` hook.

**Comment by chasingtherain** [comment]
Hi @crutchcorn 

I would like to work on this issue, however, I might need assistance from you for the implementation as this is my first major open source contribution 

If that is ok with you, could you assign this issue to me pls?

**Comment by crutchcorn** [comment]
Hey hey @chasingtherain, thank you so much for your interest in adding this feature!

Here's what you'll need to know to add this feature:

- Inside of HouseForm is the concept of a "FieldLike", which is anything that supports passing an initialValue (among other things)
- There are 3 field likes:
    1) [`FieldArrayItem`](https://github.com/crutchcorn/houseform/blob/main/lib/field-array-item/field-array-item.tsx#L32-L45)
    2) [`FieldArray`](https://github.com/crutchcorn/houseform/blob/main/lib/field-array/field-array.tsx#L29-L45)
    3) [`Field`](https://github.com/crutchcorn/houseform/blob/main/lib/field/field.tsx#L28-L44)
- These FieldLikes are controlled using a `useFieldLike` hook, [found here](https://github.com/crutchcorn/houseform/blob/main/lib/field/use-field-like.ts). You'll want to update this file to add the functionality.
    - The change validation is ran inside of the `useFieldLike` hook using [a `runFieldValidation` method](https://github.com/crutchcorn/houseform/blob/main/lib/field/use-field-like.ts#L123-L147).
    - You'll want to extend this function to accept `onMountValidate` as a new property and run it during [the `useState` validation](https://github.com/crutchcorn/houseform/blob/main/lib/field/use-field-like.ts#L110-L114)
    - You'll also want to [update the base typings of `FieldInstanceBaseProps`](https://github.com/crutchcorn/houseform/blob/main/lib/field/types.ts#L8-L13), which will update the typings for the other FieldLikes
    
    
Once this is done, you'll want to:

- [ ] Make commits following [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) naming pattern if you can. (EG: `chore: add tests` or `feat: add field validation`)
- [ ] Write tests using React Testing Library, inside of [`Field.spec.tsx`](https://github.com/crutchcorn/houseform/blob/main/lib/field/field.spec.tsx)
- [ ] Add the field to the reference docs for:
    - [ ] [`FieldProps`](https://github.com/crutchcorn/houseform/blob/main/docs/reference.md#field-props)
    - [ ] [`FieldArrayProps`](https://github.com/crutchcorn/houseform/blob/main/docs/reference.md#array-field-props)
    - [ ] [`FieldArrayItemProps`](https://github.com/crutchcorn/houseform/blob/main/docs/reference.md#array-field-item-props)

----

I know this is a big ask, but please feel free to ask me for help at any point along the way. I'm happy to answer questions either here or [in a programming Discord I help run called "Unicorn Utterances"](https://discord.gg/FMcvc6T); I'll even pair-program with you if need be :) 

Once again, thank you so much for being willing to work on this issue!

**Comment by crutchcorn** [comment]
Specific functions you'll want to update:

- [`addListenerToListenToItem`](https://github.com/crutchcorn/houseform/blob/main/lib/field/use-field-like.ts#L35-L37)
- Duplicate these but for `onMountValidate`:
    - https://github.com/crutchcorn/houseform/blob/main/lib/field/use-field-like.ts#L64-L68
    - https://github.com/crutchcorn/houseform/blob/main/lib/field/use-field-like.ts#L3-L37
- Run `runFieldValidation` inside [this `useState`](https://github.com/crutchcorn/houseform/blob/main/lib/field/use-field-like.ts#L109-L115)
- Add `onMountValidate` support to this:
    - https://github.com/crutchcorn/houseform/blob/main/lib/field/use-field-like.ts#L129-L135
- Add types to this:
    - https://github.com/crutchcorn/houseform/blob/main/lib/field/types.ts#L10

**Comment by crutchcorn** [comment]
Remember, `useState` accepts a function so:

```
const [val, setVal] = useState(0);
```

Is the same as:


```
const [val, setVal] = useState(() => 0);
```

This means that you can convert the `useState` mentioned previously with a function and call `runFieldValidation` inside of this new function
