### ISSUE TITLE
[Feature Request]: Manually trigger change detection

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/houseform#38]
### Description

Similar to how React Hook Form does this, it would be nice to provide a way to manually trigger change detection using a `FieldInstance`:

https://react-hook-form.com/api/useform/trigger

### Describe the solution you'd like

I'm imagining an API something akin to:

```jsx
const formRef = useRef(null);

// ...
const nameField = formRef.current?.getFieldValue("name");
await nameField?.validate('onSubmitValidate'); // returns validation promise
nameField.errors; // string[]
```

**Comment by hasanaktas** [comment]
is there any progress on this? I need to dynamically show or hide other inputs according to the selected value. So I need to listen to the value live.

**Comment by crutchcorn** [comment]
@hasanaktas this can already be done in HouseForm without manual change detection using `listenTo`

https://houseform.dev/guides/linked-fields.html

**Comment by hasanaktas** [comment]
![image](https://user-images.githubusercontent.com/30148248/222937142-754bdec1-8a8b-4b6f-8981-04204bed8441.png)

I have an input field where I merge Mui with your library.

![image](https://user-images.githubusercontent.com/30148248/222937192-3f987e9e-563c-4940-b381-5580c7beee45.png)

What I want to do is show the other field if name is show.

I cleaned the code for simplicity. How can I get this build?

**Comment by crutchcorn** [comment]
@hasanaktas apologies for the slow reply - your requirement really stumped me for a while since there were a dozen or more potential APIs I could implement to solve this problem.

I think I finally landed on one I like (and that seems obvious in hindsight, but I had a lot of considerations I wanted to mull over first).

Let me take a crack at implementing support for the feature you're requesting in a different ticket:

https://github.com/crutchcorn/houseform/issues/53

Closing these comments in favor of #53 as they're off topic from the current manual CD issue
